### ISSUE TITLE
REPL randomly freezing

### ISSUE THREAD

**Issue by linusg** [alimpfard/zigline#11]
Haven't seen this myself but @adkaster kindly provided a backtrace:

![image](https://github.com/alimpfard/zigline/assets/19366641/3e568e2b-e516-4117-aaad-0abbd611cc4a)

```
(lldb) process attach --pid 13610
Process 13610 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x000000018633385c libsystem_kernel.dylib`__ulock_wait2 + 8
libsystem_kernel.dylib`:
->  0x18633385c <+8>:  b.lo   0x18633387c               ; <+40>
    0x186333860 <+12>: pacibsp 
    0x186333864 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x186333868 <+20>: mov    x29, sp
Target 0: (kiesel) stopped.
Executable module set to "/Users/andrew/Source/kiesel/zig-out/bin/kiesel".
Architecture set to: arm64-apple-macosx-.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x000000018633385c libsystem_kernel.dylib`__ulock_wait2 + 8
    frame #1: 0x0000000104ffb34c kiesel`Thread.Futex.DarwinImpl.wait(ptr=0x000000016aee5da4, expect=235, timeout=(data = 0, some = '\0')) at Futex.zig:195:51
    frame #2: 0x0000000104fc11b4 kiesel`Thread.Futex.wait(ptr=0x000000016aee5da4, expect=235) at Futex.zig:25:14
    frame #3: 0x0000000104fef638 kiesel`Thread.Futex.Deadline.wait(self=0x000000016aee4fc0, ptr=0x000000016aee5da4, expect=235) at Futex.zig:1045:30
    frame #4: 0x0000000104fac5b4 kiesel`Thread.Condition.FutexImpl.wait(self=0x000000016aee5da0, mutex=0x000000016aee5bc0, timeout=(data = 0, some = '\0')) at Condition.zig:226:32
    frame #5: 0x0000000104f5a6d8 kiesel`Thread.Condition.wait(self=0x000000016aee5da0, mutex=0x000000016aee5bc0) at Condition.zig:72:19
    frame #6: 0x0000000104f599bc kiesel`main.Editor.getLine(self=0x000000016aee58e8, prompt=(ptr = "> ", len = 2)) at main.zig:1146:42
    frame #7: 0x0000000104f2bf44 kiesel`cli.repl(allocator=mem.Allocator @ 0x000000016aee67e0, realm=0x000000010836d008, options=(module = false, print_promise_rejection_warnings = true)) at cli.zig:485:43
    frame #8: 0x0000000104f268d8 kiesel`cli.main at cli.zig:731:17
    frame #9: 0x0000000104f2c928 kiesel`main at start.zig:585:37
    frame #10: 0x0000000104f2c920 kiesel`main [inlined] start.initEventLoopAndCallMain at start.zig:519:5
    frame #11: 0x0000000104f2c920 kiesel`main at start.zig:469:36
    frame #12: 0x0000000104f2c8b8 kiesel`main(c_argc=1, c_argv=0x000000016aee77f8, c_envp=0x000000016aee7808) at start.zig:484:101
    frame #13: 0x0000000185fe50e0 dyld`start + 2360
```

**Comment by alimpfard** [comment]
:thinking: stuck after pressing enter? or is it just...stuck?

**Comment by ADKaster** [comment]
Just stuck when typing

**Comment by graeme-lockley** [comment]
Yep same issue on my side running macOS - stuck solid. It is freezing both on Intel and Apple silicon.

**Comment by linusg** [comment]
Got this on Linux as well, same backtrace:

```
(gdb) bt
#0  0x0000000001f4fa22 in os.linux.x86_64.syscall4 (number=futex, arg1=140721371461048, arg2=128, arg3=48, arg4=0)
    at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/os/linux/x86_64.zig:57
#1  0x0000000001e95682 in os.linux.futex_wait (uaddr=0x7ffc3f5bb5b8, futex_op=128, val=48, timeout=0x0)
    at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/os/linux.zig:319
#2  0x0000000001e2d8dc in Thread.Futex.LinuxImpl.wait (ptr=0x7ffc3f5bb5b8, expect=48, timeout=...)
    at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/Thread/Futex.zig:254
#3  0x0000000001df1c15 in Thread.Futex.wait (ptr=0x7ffc3f5bb5b8, expect=48)
    at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/Thread/Futex.zig:25
#4  0x0000000001e20e8a in Thread.Futex.Deadline.wait (self=0x7ffc3f5ba8a0, ptr=0x7ffc3f5bb5b8, expect=48)
    at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/Thread/Futex.zig:1045
#5  0x0000000001dde6f5 in Thread.Condition.FutexImpl.wait (self=0x7ffc3f5bb5b4, mutex=0x7ffc3f5bb5bc, timeout=...)
    at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/Thread/Condition.zig:226
#6  0x0000000001d7b43c in Thread.Condition.wait (self=0x7ffc3f5bb5b4, mutex=0x7ffc3f5bb5bc)
    at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/Thread/Condition.zig:72
#7  0x0000000001d7a6c3 in main.Editor.getLine (self=0x7ffc3f5bb128, prompt=...)
    at /home/linus/.cache/zig/p/12209bf645f0dc3a683ea0d8704ddcf7151d7088d5e01c0bbd6993f6c1b2b577ad9c/src/main.zig:1146
#8  0x0000000001d4c385 in cli.repl (allocator=..., realm=0x7fd36b42b008, options=...) at cli.zig:485
#9  0x0000000001d46471 in cli.main () at cli.zig:731
#10 0x0000000001d4cfbb in start.callMain () at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/start.zig:585
#11 start.initEventLoopAndCallMain () at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/start.zig:519
#12 start.callMainWithArgs () at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/start.zig:469
#13 main (c_argc=2, c_argv=0x7ffc3f5bce28, c_envp=0x7ffc3f5bce40)
    at /nix/store/0yl7rjlb9hpbllnqlfhfdgwkhbakpbzq-zig-0.12.0-dev.2076+8fd15c6ca/lib/std/start.zig:484
(gdb) 
```

**Comment by alimpfard** [comment]
:thinking: at least this one I can try to reproduce

**Comment by alimpfard** [comment]
@linusg if you have the gdb session open, could you dump all threads' backtraces?

**Comment by linusg** [comment]
already gone, sorry :/ Will do next time!

**Comment by alimpfard** [comment]
I pushed a _possible_ fix, but it's very unlikely that we're hitting that specific issue here.
I'll keep an eye out for this, but it seems the bug is a little difficult to hit on linux...

**Comment by graeme-lockley** [comment]
Sadly @alimpfard the issue still persists - this is the trace I am seeing (thank you @linusg for the lldb instructions - very helpful for a nube)

graemelockley@Graemes-iMac-2 rebo-lang % lldb
(lldb) process attach --pid 3135
Process 3135 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007ff814e72392 libsystem_kernel.dylib`__ulock_wait2 + 10
libsystem_kernel.dylib`__ulock_wait2:
->  0x7ff814e72392 <+10>: jae    0x7ff814e7239c            ; <+20>
    0x7ff814e72394 <+12>: movq   %rax, %rdi
    0x7ff814e72397 <+15>: jmp    0x7ff814e67ccb            ; cerror_nocancel
    0x7ff814e7239c <+20>: retq
Executable module set to "/Users/graemelockley/Projects/rebo-lang/zig-out/bin/rebo".
Architecture set to: x86_64h-apple-macosx-.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007ff814e72392 libsystem_kernel.dylib`__ulock_wait2 + 10
    frame #1: 0x00000001100a9818 rebo`Thread.Futex.DarwinImpl.wait(ptr=0x00007ff7b00bc8c8, expect=177, timeout=(data = 0, some = '\0')) at Futex.zig:195:51
    frame #2: 0x000000010ffa9462 rebo`Thread.Futex.wait(ptr=0x00007ff7b00bc8c8, expect=177) at Futex.zig:25:14
    frame #3: 0x000000010ff97cdb rebo`Thread.Futex.Deadline.wait(self=0x00007ff7b00bb808, ptr=0x00007ff7b00bc8c8, expect=177) at Futex.zig:1045:30
    frame #4: 0x000000010ff31793 rebo`Thread.Condition.FutexImpl.wait(self=0x00007ff7b00bc8c4, mutex=0x00007ff7b00bc818, timeout=(data = 0, some = '\0')) at Condition.zig:227:32
    frame #5: 0x000000010fee1e1f rebo`Thread.Condition.wait(self=0x00007ff7b00bc8c4, mutex=0x00007ff7b00bc818) at Condition.zig:73:19
    frame #6: 0x000000010fee1136 rebo`zigline.main.Editor.getLine(self=0x00007ff7b00bc408, prompt=(ptr = "> ", len = 2)) at main.zig:1148:46
    frame #7: 0x000000010fee5acf rebo`main.main at main.zig:42:52
    frame #8: 0x000000010fee7581 rebo`main [inlined] start.callMain at start.zig:574:37
    frame #9: 0x000000010fee7575 rebo`main [inlined] start.initEventLoopAndCallMain at start.zig:508:5
    frame #10: 0x000000010fee7575 rebo`main at start.zig:458:36
    frame #11: 0x000000010fee7518 rebo`main(c_argc=1, c_argv=0x00007ff7b00bd6a0, c_envp=0x00007ff7b00bd6b0) at start.zig:473:101
    frame #12: 0x00007ff814b4c41f dyld`start + 1903
(lldb)

**Comment by alimpfard** [comment]
@graeme-lockley it would be great if you could post the stack trace of both threads the next time you see the hang.

**Comment by graeme-lockley** [comment]
Sure - here we go

```
graemelockley@Graemes-iMac-2 rebo-lang % lldb
(lldb) process attach --pid 16946
Process 16946 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007ff814e72392 libsystem_kernel.dylib`__ulock_wait2 + 10
libsystem_kernel.dylib`__ulock_wait2:
->  0x7ff814e72392 <+10>: jae    0x7ff814e7239c            ; <+20>
    0x7ff814e72394 <+12>: movq   %rax, %rdi
    0x7ff814e72397 <+15>: jmp    0x7ff814e67ccb            ; cerror_nocancel
    0x7ff814e7239c <+20>: retq
Executable module set to "/Users/graemelockley/Projects/rebo-lang/zig-out/bin/rebo".
Architecture set to: x86_64h-apple-macosx-.
(lldb) bt all
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007ff814e72392 libsystem_kernel.dylib`__ulock_wait2 + 10
    frame #1: 0x0000000101951f68 rebo`Thread.Futex.DarwinImpl.wait(ptr=0x00007ff7be815728, expect=75, timeout=(data = 0, some = '\0')) at Futex.zig:195:51
    frame #2: 0x0000000101851c62 rebo`Thread.Futex.wait(ptr=0x00007ff7be815728, expect=75) at Futex.zig:25:14
    frame #3: 0x00000001018404db rebo`Thread.Futex.Deadline.wait(self=0x00007ff7be8145b8, ptr=0x00007ff7be815728, expect=75) at Futex.zig:1045:30
    frame #4: 0x00000001017da203 rebo`Thread.Condition.FutexImpl.wait(self=0x00007ff7be815724, mutex=0x00007ff7be815678, timeout=(data = 0, some = '\0')) at Condition.zig:227:32
    frame #5: 0x000000010178a56f rebo`Thread.Condition.wait(self=0x00007ff7be815724, mutex=0x00007ff7be815678) at Condition.zig:73:19
    frame #6: 0x0000000101789886 rebo`zigline.main.Editor.getLine(self=0x00007ff7be815268, prompt=(ptr = "> ", len = 2)) at main.zig:1148:46
    frame #7: 0x000000010178e1ff rebo`main.main at main.zig:42:52
    frame #8: 0x0000000101790201 rebo`main [inlined] start.callMain at start.zig:574:37
    frame #9: 0x00000001017901f5 rebo`main [inlined] start.initEventLoopAndCallMain at start.zig:508:5
    frame #10: 0x00000001017901f5 rebo`main at start.zig:458:36
    frame #11: 0x0000000101790198 rebo`main(c_argc=1, c_argv=0x00007ff7be8166a0, c_envp=0x00007ff7be8166b0) at start.zig:473:101
    frame #12: 0x00007ff814b4c41f dyld`start + 1903
  thread #2
    frame #0: 0x00007ff814e72392 libsystem_kernel.dylib`__ulock_wait2 + 10
    frame #1: 0x0000000101951f68 rebo`Thread.Futex.DarwinImpl.wait(ptr=0x00007ff7be815730, expect=62, timeout=(data = 0, some = '\0')) at Futex.zig:195:51
    frame #2: 0x0000000101851c62 rebo`Thread.Futex.wait(ptr=0x00007ff7be815730, expect=62) at Futex.zig:25:14
    frame #3: 0x00000001018404db rebo`Thread.Futex.Deadline.wait(self=0x0000700005d71af8, ptr=0x00007ff7be815730, expect=62) at Futex.zig:1045:30
    frame #4: 0x00000001017da203 rebo`Thread.Condition.FutexImpl.wait(self=0x00007ff7be81572c, mutex=0x00007ff7be815688, timeout=(data = 0, some = '\0')) at Condition.zig:227:32
    frame #5: 0x000000010178a56f rebo`Thread.Condition.wait(self=0x00007ff7be81572c, mutex=0x00007ff7be815688) at Condition.zig:73:19
    frame #6: 0x0000000101948094 rebo`zigline.main.Editor.controlThreadMain(self=0x00007ff7be815268) at main.zig:1291:42
    frame #7: 0x00000001018400eb rebo`Thread.callFn__anon_16652(args=<unavailable>) at Thread.zig:412:13
    frame #8: 0x00000001017d9ed3 rebo`Thread.PosixThreadImpl.spawn__anon_12436.Instance.entryFn(raw_arg=0x0000600000c08020) at Thread.zig:685:30
    frame #9: 0x00007ff814ea61d3 libsystem_pthread.dylib`_pthread_start + 125
    frame #10: 0x00007ff814ea1bd3 libsystem_pthread.dylib`thread_start + 15
(lldb) 
```

**Comment by alimpfard** [comment]
Can you test with the latest commit on `master`? I did some very limited testing and it seemed to have been fixed (or at least made less likely)

**Comment by graeme-lockley** [comment]
so far so good... it hasn't hung once this morning

well done @alimpfard and thank you

**Comment by linusg** [comment]
Seems fine for now, let's close until someone can provide a new freeze with backtrace(s).
